### ISSUE TITLE
Naming disadvantages

### ISSUE THREAD

**Issue by arbox** [blazeeboy/amun#2]
Hi @blazeeboy ,

thank you for this interesting project!

I'm afraid of possible collisions with the new `remacs` port https://github.com/Wilfred/remacs by @Wilfred.

What do you think?

**Comment by blazeeboy** [comment]
Oh yes that is correct, thanks for the heads up, I'm afraid I have to rename this project, better now than later.
Any suggestions for a name?

**Comment by arbox** [comment]
Don't know :) Rubymacs? Rumacs? Racs? EmacsR? Rove?
There're plenty of other ErsatzEmacs implementations...
