### ISSUE TITLE
Start up config files

### ISSUE THREAD

**Issue by emad-elsaid** [blazeeboy/amun#5]
* upon starting amun it should create ~/.amun/Gemfile if it doesn't exist (usual bundler Gemfile initial content), then bundle install to create Gemfile.lock
* upon starting amun it should create ~/.amun/init.rb if it doesn't exist (empty file)
* upon starting amun it should load the Gemfile, if a gem is missing it should `bundle install` then load it again.
* after loading the Gemfile successfully it should run `~/init.rb` script for initialization config by the user.
* if any error happened it should be displayed in the echo area

**Comment by blazeeboy** [comment]
@adham90 this could be interesting for you
